dist: trusty
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --only-upgrade cmake
  - gem install bundler
language: ruby
rvm:
  - 2.2.2
script:
  - 'createuser exercism --superuser && createdb -O exercism exercism_test'
  - 'RACK_ENV=test CI=1 bundle exec rake db:migrate test_with_coverage'
  - '( cd frontend && npm install && lineman spec-ci )'
  - "! git grep ' $' -- \\*.rb"
cache:
  - bundler
